server:
  servlet:
    context-path: /backstage
  port: 8082
  
  

mybatis:
  mapper-locations: classpath:maps/*.xml


spring: 
  resources:
    static-locations: classpath:public,classpath:static,file:D:\system_backstage
  datasource:
    url: jdbc:mysql://localhost:3306/mgj
    username: root
    password: 123
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      # 下面为连接池的补充设置，应用到上面所有数据源中
      # 初始化大小，最小，最大
      initial-size: 15
      min-idle: 15
      max-active: 50
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
